---
- name: Install Certbot
  import_role:
    name: geerlingguy.certbot
  vars:
    certbot_admin_email: "{{ admin_email | default(info@example.com) }}"
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_minute: "20"
    certbot_auto_renew_hour: "5"
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services:
      - nginx
    certbot_certs:
      - domains:
        - "{{ project_url }}"