---

- name: Add Nginx Config (redhat)
  template:
    src: nginx_redhat.j2
    dest: "/etc/nginx/conf.d/{{ project_url }}.conf"
  notify: restart nginx

- name: Change storage permissions
  file:
    path: "/home/{{ project_url }}/storage"
    owner: nginx
    group: nginx
    mode: 0755
    state: directory
    recurse: yes